# Generated by Django 4.2.7 on 2026-01-13 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('error', 'Error'), ('timeout', 'Timeout')], max_length=20)),
                ('execution_time', models.IntegerField(default=0)),
                ('memory_usage', models.IntegerField(default=0)),
                ('console_output', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.testcase')),
            ],
            options={
                'db_table': 'test_results',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_content', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C')], max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('late', 'Late'), ('missing', 'Missing')], default='submitted', max_length=20)),
                ('auto_grade_score', models.IntegerField(default=0)),
                ('manual_adjustment', models.IntegerField(default=0)),
                ('final_score', models.IntegerField(default=0)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('is_graded', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.question')),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
