# Generated by Django 4.2.7 on 2026-01-23 10:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_code", models.TextField()),
                ("time_spent", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "assignment_progress",
            },
        ),
        migrations.CreateModel(
            name="GradebookEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("final_score", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[("graded", "Graded"), ("submitted", "Submitted")],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "gradebook_entries",
            },
        ),
        migrations.CreateModel(
            name="SubmissionAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_number", models.IntegerField(default=1)),
                ("code_blob_ref", models.CharField(blank=True, max_length=255)),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("fail", "Fail"),
                            ("error", "Error"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="assignments.assignmentquestion",
                    ),
                ),
            ],
            options={
                "db_table": "submission_attempts",
                "ordering": ["student", "assignment_question", "-attempt_number"],
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("test_case_id", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("pass", "Pass"), ("fail", "Fail")], max_length=10
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="submissions.submissionattempt",
                    ),
                ),
            ],
            options={
                "db_table": "test_result_details",
            },
        ),
    ]
