# Generated by Django 4.2.7 on 2026-01-23 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("submissions", "0001_initial"),
        ("assignments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionattempt",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gradebookentry",
            name="content_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.contentitem",
            ),
        ),
        migrations.AddField(
            model_name="gradebookentry",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assignmentprogress",
            name="assignment_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="assignments.assignmentquestion",
            ),
        ),
        migrations.AddField(
            model_name="assignmentprogress",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gradebookentry",
            unique_together={("student", "content_item")},
        ),
        migrations.AlterUniqueTogether(
            name="assignmentprogress",
            unique_together={("student", "assignment_question")},
        ),
    ]
