# Generated by Django 4.2.7 on 2026-01-13 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='test_results',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='submissions.testresult'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assignment', 'question', 'student')},
        ),
    ]
