# Generated by Django 4.2.7 on 2026-01-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentprogress",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
