# Generated by Django 6.0.1 on 2026-01-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback_tags',
            field=models.CharField(blank=True, help_text="Comma-separated tags e.g. 'Logic Error, Syntax'", max_length=255),
        ),
        migrations.AddField(
            model_name='submission',
            name='time_spent',
            field=models.IntegerField(default=0, help_text='Time spent in minutes'),
        ),
    ]
