# Generated by Django 4.2.7 on 2026-01-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_feedback_tags_submission_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text='Last time student was active on this question', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When student first opened the question', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time_spent',
            field=models.IntegerField(default=0, help_text='Time spent in seconds'),
        ),
    ]
