# Generated by Django 4.2.7 on 2026-01-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0003_assignmentprogress_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionattempt",
            name="feedback_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="submissionattempt",
            name="manual_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
