# Generated by Django 4.2.7 on 2026-01-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submissionattempt_feedback_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='actual_output',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testresult',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
