# Generated by Django 4.2.7 on 2026-01-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "submissions",
            "0004_submission_last_activity_at_submission_started_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="embedding_x",
            field=models.FloatField(
                blank=True, help_text="UMAP X coordinate", null=True
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="embedding_y",
            field=models.FloatField(
                blank=True, help_text="UMAP Y coordinate", null=True
            ),
        ),
    ]
