# Generated by Django 4.2.7 on 2026-01-20 06:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0005_submission_embedding_x_submission_embedding_y"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="embedding_x",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="embedding_y",
        ),
    ]
