# Generated by Django 4.2.7 on 2026-01-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_testresult_actual_output_testresult_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionattempt',
            name='source_code',
            field=models.TextField(blank=True),
        ),
    ]
