# Generated by Django 4.2.7 on 2026-01-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0006_submissionattempt_source_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradebookentry",
            name="points_earned",
            field=models.IntegerField(default=0),
        ),
    ]
