# Generated by Django 4.2.7 on 2026-02-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0007_add_points_to_gradebook"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="execution_time_ms",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
