# Generated by Django 4.2.7 on 2026-02-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0008_testresult_execution_time_ms"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionattempt",
            name="detected_keywords",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
