# Generated by Django 4.2.7 on 2026-02-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0009_submissionattempt_detected_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testresult",
            name="status",
            field=models.CharField(
                choices=[("pass", "Pass"), ("fail", "Fail")], max_length=20
            ),
        ),
    ]
