# Generated by Django 4.2.7 on 2026-02-17 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0010_alter_testresult_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradebookentry",
            name="completion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gradebookentry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gradebookentry",
            name="status",
            field=models.CharField(
                choices=[("graded", "Graded"), ("pending", "Pending")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
