# Generated by Django 4.2.7 on 2026-02-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0011_gradebookentry_completion_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionattempt",
            name="ai_analysis_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="submissionattempt",
            name="code_blob_ref",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
