# Generated by Django 4.2.7 on 2026-02-19 17:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0005_auto_20260216_0625"),
        ("submissions", "0012_submissionattempt_ai_analysis_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysisTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("task_ids", models.JSONField(default=list)),
                ("total_batches", models.IntegerField(default=0)),
                ("completed_batches", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tasks",
                        to="assignments.assignment",
                    ),
                ),
            ],
            options={
                "db_table": "ai_analysis_tasks",
                "ordering": ["-created_at"],
            },
        ),
    ]
