# Generated by Django 4.2.7 on 2026-02-20 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0005_auto_20260216_0625"),
        ("submissions", "0013_aianalysistask"),
    ]

    operations = [
        migrations.AddField(
            model_name="aianalysistask",
            name="analyzed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aianalysistask",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="aianalysistask",
            name="total_submissions",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="aianalysistask",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_analysis_tasks",
                to="assignments.assignment",
            ),
        ),
        migrations.AlterField(
            model_name="aianalysistask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
