# Generated by Django 4.2.7 on 2026-02-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0014_ai_analysis_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="aianalysistask",
            name="log_output",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
