# Generated by Django 4.2.7 on 2026-02-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0015_add_log_output_to_ai_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionattempt",
            name="response_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
