# Generated by Django 4.2.7 on 2026-02-11 15:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("submissions", "0007_add_points_to_gradebook"),
        ("assignments", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("detected_keywords", models.JSONField(default=list)),
                ("umap_x", models.FloatField(blank=True, null=True)),
                ("umap_y", models.FloatField(blank=True, null=True)),
                ("ai_feedback", models.TextField(blank=True)),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="submissions.submissionattempt",
                    ),
                ),
            ],
            options={
                "db_table": "submission_analysis",
            },
        ),
        migrations.CreateModel(
            name="ProblemAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("test_case_id", models.CharField(max_length=50)),
                ("pass_count", models.IntegerField(default=0)),
                ("fail_count", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="assignments.question",
                    ),
                ),
            ],
            options={
                "db_table": "problem_analytics",
                "unique_together": {("question", "test_case_id")},
            },
        ),
    ]
