# Generated by Django 4.2.7 on 2026-01-23 10:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssignmentQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("custom_points", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "assignment_questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("assignment", "Assignment"),
                            ("quiz", "Quiz"),
                            ("material", "Material"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=False)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "content_items",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("starter_code", models.TextField(blank=True)),
                ("reference_solution", models.TextField(blank=True)),
                ("test_cases", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "contentitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="assignments.contentitem",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("practice", "Practice"), ("exam", "Exam")],
                        default="practice",
                        max_length=20,
                    ),
                ),
                ("points_total", models.IntegerField(default=100)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        default="Medium",
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "assignments",
            },
            bases=("assignments.contentitem",),
        ),
    ]
