# Generated by Django 4.2.7 on 2026-01-23 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assignments", "0001_initial"),
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="classes.module",
            ),
        ),
        migrations.AddField(
            model_name="assignmentquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="assignments.question"
            ),
        ),
        migrations.AddField(
            model_name="assignmentquestion",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="assignments.assignment"
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="questions",
            field=models.ManyToManyField(
                related_name="assignments",
                through="assignments.AssignmentQuestion",
                to="assignments.question",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignmentquestion",
            unique_together={("assignment", "question")},
        ),
    ]
