# Generated by Django 4.2.7 on 2026-02-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
