# Generated by Django 4.2.7 on 2026-01-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, help_text='Hint to help students solve the problem'),
        ),
        migrations.AddField(
            model_name='question',
            name='starter_code',
            field=models.TextField(blank=True, help_text='Starter code template for students'),
        ),
    ]
