# Generated by Django 4.2.7 on 2026-02-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0003_question_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.CharField(default="General", max_length=100),
        ),
        migrations.AddField(
            model_name="question",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("Easy", "Easy"), ("Medium", "Medium"), ("Hard", "Hard")],
                default="Medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="question",
            name="point_value",
            field=models.IntegerField(default=100),
        ),
    ]
