# Generated by Django 4.2.7 on 2026-02-16 06:25

from django.db import migrations
from django.utils.text import slugify

def migrate_practice_questions(apps, schema_editor):
    try:
        PracticeQuestion = apps.get_model('gamification', 'PracticeQuestion')
        Question = apps.get_model('assignments', 'Question')
    except LookupError:
        return

    for pq in PracticeQuestion.objects.all():
        if not Question.objects.filter(id=pq.id).exists():
            base_slug = slugify(pq.title) if pq.title else "question"
            slug = f"{base_slug}-{str(pq.id)[:8]}"
            
            difficulty = pq.difficulty.capitalize() if pq.difficulty else 'Medium'
            if difficulty not in ['Easy', 'Medium', 'Hard']:
                difficulty = 'Medium'

            Question.objects.create(
                id=pq.id,
                title=pq.title,
                slug=slug,
                description=pq.description if pq.description else "",
                starter_code=pq.starter_code if pq.starter_code else "",
                test_cases=pq.test_cases if pq.test_cases else [],
                difficulty=difficulty,
                category=pq.category if pq.category else "General",
                point_value=pq.point_value if pq.point_value else 100,
                config=pq.config if pq.config else {},
                is_active=pq.is_active,
                created_by_id=pq.created_by_id,
                # Note: auto_now_add might override created_at, but we try anyway
                created_at=pq.created_at,
                updated_at=pq.updated_at
            )

def reverse_migrate_practice_questions(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0004_question_category_question_config_and_more"),
        ("gamification", "0003_practicequestion_config"),
    ]

    operations = [
        migrations.RunPython(migrate_practice_questions, reverse_migrate_practice_questions),
    ]
