# Generated by Django 4.2.7 on 2026-02-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0005_auto_20260216_0625"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("coding", "Coding"), ("mcq", "Multiple Choice")],
                default="coding",
                max_length=20,
            ),
        ),
    ]
