# Generated by Django 4.2.7 on 2026-02-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0006_question_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="questions_released",
            field=models.BooleanField(default=False),
        ),
    ]
