# Generated by Django 4.2.7 on 2026-03-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0007_assignment_questions_released"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentquestion",
            name="umap_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
