# Generated by Django 4.2.7 on 2026-01-13 05:46

import classes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('theme_color', models.CharField(default='#6366f1', max_length=7)),
                ('bg_pattern', models.CharField(default='bg-indigo-600', max_length=50)),
                ('join_code', models.CharField(default=classes.models.generate_join_code, max_length=10, unique=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('semester', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'db_table': 'classes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('ta', 'Teaching Assistant'), ('student', 'Student')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.class')),
            ],
            options={
                'db_table': 'enrollments',
                'ordering': ['-joined_at'],
            },
        ),
    ]
