# Generated by Django 4.2.7 on 2026-02-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0003_announcement_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
