# Generated by Django 4.2.7 on 2026-01-27 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gamification", "0001_initial"),
    ]

    operations = []
