# Generated by Django 4.2.7 on 2026-02-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamification", "0002_auto_20260127_0725"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicequestion",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
