# Generated by Django 4.2.7 on 2026-02-16 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0005_auto_20260216_0625"),
        ("gamification", "0003_practicequestion_config"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="practicequestion",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="practiceprogress",
            name="practice_pr_practic_703dfd_idx",
        ),
        migrations.RemoveIndex(
            model_name="practicequestion",
            name="practice_qu_difficu_ce3de9_idx",
        ),
        migrations.RemoveIndex(
            model_name="practicequestion",
            name="practice_qu_is_acti_5fbe3a_idx",
        ),
        migrations.RemoveIndex(
            model_name="practicesubmission",
            name="practice_su_student_8d2001_idx",
        ),
        migrations.AddField(
            model_name="practiceprogress",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practice_progress",
                to="assignments.question",
            ),
        ),
        migrations.AddField(
            model_name="practicequestionlibrary",
            name="practice_question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gamification.practicequestion",
            ),
        ),
        migrations.AddField(
            model_name="practicesubmission",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practice_submissions",
                to="assignments.question",
            ),
        ),
        migrations.AlterField(
            model_name="practiceprogress",
            name="practice_question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="gamification.practicequestion",
            ),
        ),
        migrations.AlterField(
            model_name="practicequestionlibrary",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.question",
            ),
        ),
        migrations.AlterField(
            model_name="practicesubmission",
            name="practice_question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="gamification.practicequestion",
            ),
        ),
        migrations.AddIndex(
            model_name="practiceprogress",
            index=models.Index(
                fields=["question", "is_completed"],
                name="practice_pr_questio_67fd97_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="practicesubmission",
            index=models.Index(
                fields=["student", "question"], name="practice_su_student_f590b0_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="practicequestion",
            table=None,
        ),
    ]
