# Generated by Django 4.2.7 on 2026-02-16 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0005_auto_20260216_0625"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gamification", "0005_auto_20260216_0634"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="practiceprogress",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="practicequestionlibrary",
            name="practice_question",
        ),
        migrations.RemoveField(
            model_name="practicesubmission",
            name="practice_question",
        ),
        migrations.AlterField(
            model_name="practiceprogress",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practice_progress",
                to="assignments.question",
            ),
        ),
        migrations.AlterField(
            model_name="practicequestionlibrary",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="assignments.question"
            ),
        ),
        migrations.AlterField(
            model_name="practicesubmission",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practice_submissions",
                to="assignments.question",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="practiceprogress",
            unique_together={("student", "question")},
        ),
        migrations.RemoveField(
            model_name="practiceprogress",
            name="practice_question",
        ),
        migrations.DeleteModel(
            name="PracticeQuestion",
        ),
    ]
