# Generated by Django 4.2.7 on 2026-03-02 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0008_assignmentquestion_umap_url"),
        ("gamification", "0007_daily_weekly_leaderboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicequestionlibrary",
            name="hide_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="practicequestionlibrary",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="practicequestionlibrary",
            name="source_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="library_questions",
                to="assignments.assignment",
            ),
        ),
        migrations.AddIndex(
            model_name="practicequestionlibrary",
            index=models.Index(
                fields=["is_hidden"], name="practice_qu_is_hidd_43f513_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practicequestionlibrary",
            index=models.Index(
                fields=["hide_until"], name="practice_qu_hide_un_0b089a_idx"
            ),
        ),
    ]
